"""Trusted execution helpers for the first backend-facing TrustAero fragment."""

from trustaero.execution.compiler import (
    CompiledQuery,
    ExecutionCompileError,
    TableBindings,
    compile_approved_physical_plan,
    compile_validated_plan,
)
from trustaero.execution.duckdb import (
    DuckDBUnavailable,
    QueryExecutionResult,
    execute_with_connection,
    execute_with_duckdb,
    materialize_query_result,
)
from trustaero.execution.explain import PhysicalPlanObservation, observe_duckdb_plan
from trustaero.execution.lineage import (
    LineageInstrumentationError,
    SourceLineageCaptureResult,
    capture_source_lineage,
)
from trustaero.execution.record_lineage import (
    CompactRecordLineageArtifact,
    CompactRecordLineageCaptureResult,
    CompactRecordLineageExecutionResult,
    CompiledRecordLineagePlan,
    DatabaseDigestRecordLineageExecutionResult,
    OrdinalRecordLineageArtifact,
    OrdinalRecordLineageCaptureResult,
    OrdinalRecordLineageExecutionResult,
    RecordLineageArtifact,
    RecordLineageArtifactVerification,
    RecordLineageCaptureResult,
    RecordLineageCaptureSpec,
    RecordLineageEdge,
    RecordLineageExecutionResult,
    capture_compact_record_lineage,
    capture_record_lineage,
    compile_record_lineage_plan,
    execute_compact_record_lineage_with_connection,
    execute_database_digest_record_lineage_with_connection,
    execute_ordinal_record_lineage_with_connection,
    execute_record_lineage_with_connection,
    verify_compact_record_lineage_artifact,
    verify_database_digest_record_lineage_artifact,
    verify_ordinal_record_lineage_artifact,
    verify_record_lineage_artifact,
)

__all__ = [
    "CompiledQuery",
    "CompiledRecordLineagePlan",
    "CompactRecordLineageArtifact",
    "CompactRecordLineageCaptureResult",
    "CompactRecordLineageExecutionResult",
    "DatabaseDigestRecordLineageExecutionResult",
    "DuckDBUnavailable",
    "ExecutionCompileError",
    "LineageInstrumentationError",
    "OrdinalRecordLineageArtifact",
    "OrdinalRecordLineageCaptureResult",
    "OrdinalRecordLineageExecutionResult",
    "PhysicalPlanObservation",
    "QueryExecutionResult",
    "RecordLineageArtifact",
    "RecordLineageArtifactVerification",
    "RecordLineageCaptureResult",
    "RecordLineageCaptureSpec",
    "RecordLineageEdge",
    "RecordLineageExecutionResult",
    "TableBindings",
    "SourceLineageCaptureResult",
    "capture_compact_record_lineage",
    "capture_source_lineage",
    "capture_record_lineage",
    "compile_record_lineage_plan",
    "compile_approved_physical_plan",
    "compile_validated_plan",
    "execute_compact_record_lineage_with_connection",
    "execute_database_digest_record_lineage_with_connection",
    "execute_ordinal_record_lineage_with_connection",
    "execute_record_lineage_with_connection",
    "execute_with_connection",
    "execute_with_duckdb",
    "materialize_query_result",
    "observe_duckdb_plan",
    "verify_compact_record_lineage_artifact",
    "verify_database_digest_record_lineage_artifact",
    "verify_ordinal_record_lineage_artifact",
    "verify_record_lineage_artifact",
]
