"""Stable enums shared by schemas, validator output, tests, and the paper artifact.

枚举值属于公开数据契约。变量名或可读消息可以改进，但这些字符串在同一 IR
版本内应保持稳定，便于复现实验和按错误类型统计结果。
"""

from enum import StrEnum


class PolicyDecision(StrEnum):
    """XACML-inspired policy decisions; not TrustAero validation outcomes."""

    PERMIT = "PERMIT"
    DENY = "DENY"
    INDETERMINATE = "INDETERMINATE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ValidationStatus(StrEnum):
    """TrustAero-defined handling states for a complete candidate plan."""

    ACCEPT = "ACCEPT"
    REWRITE = "REWRITE"
    CLARIFY = "CLARIFY"
    REJECT = "REJECT"


class ObligationType(StrEnum):
    VERSION_PIN = "VERSION_PIN"
    MASK = "MASK"
    GENERALIZE_LOCATION = "GENERALIZE_LOCATION"
    MIN_GROUP_SIZE = "MIN_GROUP_SIZE"
    EXPORT_CONTROL = "EXPORT_CONTROL"
    LINEAGE_CAPTURE = "LINEAGE_CAPTURE"


class LineageLevel(StrEnum):
    NONE = "none"
    SOURCE = "source"
    RECORD = "record"


class ReasonCode(StrEnum):
    """Machine-stable diagnostics; messages are intentionally not the API key."""

    PLAN_PARSE_ERROR = "PLAN_PARSE_ERROR"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    UNKNOWN_OPERATOR = "UNKNOWN_OPERATOR"
    INVALID_OPERATOR_ARGUMENT = "INVALID_OPERATOR_ARGUMENT"
    DUPLICATE_OPERATOR_ID = "DUPLICATE_OPERATOR_ID"
    UNBOUND_REFERENCE = "UNBOUND_REFERENCE"
    CYCLIC_PLAN = "CYCLIC_PLAN"
    UNREACHABLE_OPERATOR = "UNREACHABLE_OPERATOR"
    OUTPUT_OPERATOR_UNKNOWN = "OUTPUT_OPERATOR_UNKNOWN"
    UNKNOWN_DATASET = "UNKNOWN_DATASET"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    PURPOSE_MISSING = "PURPOSE_MISSING"
    POLICY_DENIED = "POLICY_DENIED"
    POLICY_INDETERMINATE = "POLICY_INDETERMINATE"
    POLICY_NOT_APPLICABLE = "POLICY_NOT_APPLICABLE"
    POLICY_CONFLICT = "POLICY_CONFLICT"
    VERSION_UNRESOLVED = "VERSION_UNRESOLVED"
    SPATIAL_PRECISION_EXCEEDED = "SPATIAL_PRECISION_EXCEEDED"
    MASK_REQUIRED = "MASK_REQUIRED"
    MIN_GROUP_SIZE_REQUIRED = "MIN_GROUP_SIZE_REQUIRED"
    EXPORT_FORBIDDEN = "EXPORT_FORBIDDEN"
    LINEAGE_REQUIRED = "LINEAGE_REQUIRED"
    OBLIGATION_CONFLICT = "OBLIGATION_CONFLICT"
    REWRITE_CYCLE_DETECTED = "REWRITE_CYCLE_DETECTED"
    REWRITE_DID_NOT_CONVERGE = "REWRITE_DID_NOT_CONVERGE"
